### ISSUE TITLE
Gitter Channel?

### ISSUE THREAD

**Issue by dispalt** [nokia/akka-typed-persistence#11]
Would you be interested in setting up a gitter channel?

I am using this all and it's working great so far.

**Comment by dilation** [comment]
I guess we could have a gitter channel (though I don't think it'll have a big traffic :-). I'll look into setting up one.

It's good to hear this is working for you. Could you tell more about what are you using it for?

**Comment by dispalt** [comment]
Basically just better actors =)

I got it working with ClusterSharding this weekend, and I was pleasantly surprised at how easily mixed typed/untyped actors work. I probably have Roland to thank for that.

I also upgraded it to 2.5.0-RC2 if you want a PR, and it worked great.  I am a little worried this may not get much love, but like I said it's working pretty well.

**Comment by dispalt** [comment]
I also use it together with Eff which is excellent for multiple effect stacks

**Comment by dilation** [comment]
Ok, I've created a gitter room: https://gitter.im/nokia/akka-typed-persistence

Yes, we're also using it with cluster sharding, and indeed, interop with untyped actors mostly works.

Regarding Akka 2.5: I've planned to wait for 2.5 final before upgrading. After that, a PR would be gladly accepted.
