### ISSUE TITLE
Replacing Behavior

### ISSUE THREAD

**Issue by dispalt** [nokia/akka-typed-persistence#6]
Is there a way to replace behavior like there is in normal akka-typed, similar to this blog post?

https://blog.scalac.io/2015/04/30/leszek-akka-typed.html

**Comment by dilation** [comment]
At the moment, there is no way to do that. (The best workaround is replacing the state, and handling that in the behavior). However, I'd like to have that ability. I just haven't figured out how to do that, without complicating the current API, and preserving the ability to save and restore snapshots.

**Comment by dispalt** [comment]
Makes sense, thanks for the explanation!
