### ISSUE TITLE
Access to sequenceNr

### ISSUE THREAD

**Issue by dispalt** [nokia/akka-typed-persistence#9]
It would be nice to get access to the sequenceNr from within the actor.  I have a process that depends on replaying at a certain event and knowing the seqNr is the best way to achieve that, also it seems like it would be useful for others.

Thoughts?

**Comment by durban** [comment]
Access to `sequenceNr` was not included originally because it seemed like a low-level detail (also, we didn't need it). Although it makes sense that there would be cases when it's necessary.

Could you write some more about your use case (like how and when are you using the `sequenceNr`)?

**Comment by dispalt** [comment]
So the biggest more specific use case I have is as follows:

* You can think of persistence as representing a two-level hash map, or a hash of an indexed list, where the only efficient way to slice that list is using sequence numbers. 
* During a persistence query, I'd like to be able to read from a point in time (which naturally means sequence numbers).
* So if I wanted to read a query from `now` until I terminate, I would ask the actor for its sequence number.  Then use a persistent query to fetch starting at that sequence number, with the max seqNr being `Long.MaxValue`.
* If I had a really big single actor (lots of events stored).  I may even want to store a seqNr at the beginning of a day.  Then to aggregate multiple days, I could late filter my events, but start with something closer thanks to my daily rollup `seqNr`.

Like I mentioned in the first bullet point, seqNr is basically the only efficient "key" on persistent actors and therefore is worth exposing.

**Comment by dilation** [comment]
Would adding the following operation to `PersistenceApi` work for you?

```scala
sealed trait PersistenceApi[A, D, S] {

  ...

  /**
   * Returns the sequence number
   * of the last written (or replayed)
   * event.
   */
  def lastSequenceNr: Proc[Long]
}
```

If yes, I think that could be implemented quite easily.
